- name: Ensure necessary directories exist
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - "{{ download_destination }}"
    - "{{ extract_to }}"

- name: Download binaries
  get_url:
    url: "{{ url }}"
    dest: "{{ download_destination }}"
    # TODO(sigmavirus24): When OSA starts using ansible 2.0, switch to
    # checksum
    #checksum: "sha256:{{ sha256sum }}"
    sha256sum: "{{ sha256sum }}"

- name: Extract binaries
  unarchive:
    copy: no
    dest: "{{ extract_to }}"
    src: "{{ extract_from }}"

- name: Hard link the binaries to /usr/local/bin
  file:
    src: "{{ binaries_path }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: hard
  with_items: "{{ binaries_to_extract }}"
  when: binaries_to_extract is defined
